export const ROOM_CODE_MIN_LENGTH = 3;
export const ROOM_CODE_MAX_LENGTH = 12;
export const PLAYER_NAME_MIN_LENGTH = 1;
export const PLAYER_NAME_MAX_LENGTH = 24;
export const DEFAULT_TARGET_TIMELINE_CARD_COUNT = 10;
export const MIN_TARGET_TIMELINE_CARD_COUNT = 3;
export const MAX_TARGET_TIMELINE_CARD_COUNT = 30;
