import type {
  GamePageAssemblyModel,
  LoadedGamePageController,
} from "../GamePage.types";

export function buildGamePageAssemblyModel(
  controller: LoadedGamePageController,
): GamePageAssemblyModel {
  return {
    actions: {
      canClaimChallenge: controller.canClaimChallenge,
      canConfirmBeatPlacement: controller.canConfirmBeatPlacement,
      canConfirmReveal: controller.canConfirmReveal,
      canConfirmTurnPlacement: controller.canConfirmTurnPlacement,
      canResolveChallengeWindow: controller.canResolveChallengeWindow,
      canUseBuyCard: controller.canUseBuyCard,
      canUseSkipTrack: controller.canUseSkipTrack,
      challengeActionBody: controller.challengeActionBody,
      challengeActionTitle: controller.challengeActionTitle,
      challengeCountdownLabel: controller.challengeCountdownLabel,
      currentPlayerTtCount: controller.currentPlayerTtCount,
      getPlayerName: controller.getPlayerName,
      handleBuyTimelineCardWithTt: controller.handleBuyTimelineCardWithTt,
      handleClaimChallenge: controller.handleClaimChallenge,
      handleConfirmReveal: controller.handleConfirmReveal,
      handlePlaceCard: controller.handlePlaceCard,
      handlePlaceChallenge: controller.handlePlaceChallenge,
      handleResolveChallengeWindow: controller.handleResolveChallengeWindow,
      handleSkipTrackWithTt: controller.handleSkipTrackWithTt,
      roomState: controller.roomState,
      showHelperLabels: controller.showHelperLabels,
    },
    errorMessage: controller.errorMessage,
    header: {
      currentPlayerId: controller.currentPlayerId,
      leadingPlayers: controller.leadingPlayers,
      menuTabs: controller.menuTabs,
      roomState: controller.roomState,
      showMiniStandings: controller.showMiniStandings,
      showPhaseChip: controller.showPhaseChip,
      showRoomCodeChip: controller.showRoomCodeChip,
      showTimelineHints: controller.showTimelineHints,
      showTurnNumberChip: controller.showTurnNumberChip,
      statusBadgeText: controller.statusBadgeText,
      statusDetailText: controller.statusDetailText,
      updateViewPreferences: controller.updateViewPreferences,
    },
    timeline: {
      header: {
        canChangeTimelineView: controller.canChangeTimelineView,
        canToggleView: controller.canToggleTimelineView,
        cardCount: controller.visibleTimelineCardCount,
        onToggleTimelineView: controller.setTimelineView,
        timelineView: controller.timelineView,
        title: controller.visibleTimelineTitle,
      },
      interaction: {
        challengeMarkerTone: controller.challengeMarkerTone,
        challengerChosenSlotIndex: controller.visibleChallengeChosenSlot,
        disabledSlotIndexes: controller.disabledTimelineSlots,
        onSelectSlot: controller.setSelectedSlotIndex,
        originalChosenSlotIndex: controller.visibleOriginalChosenSlot,
        previewCard: controller.visiblePreviewCard,
        previewSlotIndex: controller.visiblePreviewSlot,
        selectable: !controller.isViewingOwnTimeline && controller.canSelectSlot,
        selectedSlotIndex: controller.selectedSlotIndex,
      },
      render: {
        celebrationCard: controller.challengeSuccessCelebrationCard,
        celebrationKey: controller.challengeSuccessCelebrationKey,
        celebrationMessage: controller.challengeSuccessMessage,
        hiddenCardMode: controller.hiddenCardMode,
        hint: controller.visibleTimelineHint,
        showCorrectPlacementPreview: controller.showCorrectPlacementPreview,
        showCorrectionPreview: controller.showCorrectionPreview,
        showDevAlbumInfo: controller.isHost && controller.showDevAlbumInfo,
        showDevCardInfo: controller.isHost && controller.showDevCardInfo,
        showDevGenreInfo: controller.isHost && controller.showDevGenreInfo,
        showDevYearInfo: controller.isHost && controller.showDevYearInfo,
        showHint: controller.showTimelineHints,
        theme: controller.theme,
        timelineCards: controller.visibleTimelineCards,
        timelineView: controller.timelineView,
      },
    },
  };
}
