import type {
  GamePageAssemblyModel,
  LoadedGamePageController,
} from "../GamePage.types";

export function buildGamePageAssemblyModel(
  controller: LoadedGamePageController,
): GamePageAssemblyModel {
  return {
    actions: {
      buyTimelineCardActionStatus: controller.buyTimelineCardActionStatus,
      canClaimChallenge: controller.canClaimChallenge,
      canConfirmBeatPlacement: controller.canConfirmBeatPlacement,
      canConfirmReveal: controller.canConfirmReveal,
      canConfirmTurnPlacement: controller.canConfirmTurnPlacement,
      canResolveChallengeWindow: controller.canResolveChallengeWindow,
      canSkipOfflinePlayer: controller.canSkipOfflinePlayer,
      canUseBuyCard: controller.canUseBuyCard,
      canUseSkipTrack: controller.canUseSkipTrack,
      challengeActionBody: controller.challengeActionBody,
      challengeActionTitle: controller.challengeActionTitle,
      claimChallengeActionStatus: controller.claimChallengeActionStatus,
      confirmRevealActionStatus: controller.confirmRevealActionStatus,
      currentPlayerId: controller.currentPlayerId,
      currentPlayerTtCount: controller.currentPlayerTtCount,
      getPlayerName: controller.getPlayerName,
      handleBuyTimelineCardWithTt: controller.handleBuyTimelineCardWithTt,
      handleClaimChallenge: controller.handleClaimChallenge,
      handleConfirmReveal: controller.handleConfirmReveal,
      handlePlaceCard: controller.handlePlaceCard,
      handlePlaceChallenge: controller.handlePlaceChallenge,
      handleResolveChallengeWindow: controller.handleResolveChallengeWindow,
      handleSkipTrackWithTt: controller.handleSkipTrackWithTt,
      handleSkipTurn: controller.handleSkipTurn,
      isBuyTimelineCardPending: controller.isBuyTimelineCardPending,
      isCurrentPlayerTurn: controller.isCurrentPlayerTurn,
      isClaimChallengePending: controller.isClaimChallengePending,
      isConfirmRevealPending: controller.isConfirmRevealPending,
      isPlaceCardPending: controller.isPlaceCardPending,
      isPlaceChallengePending: controller.isPlaceChallengePending,
      isSkipTrackPending: controller.isSkipTrackPending,
      isSkipTurnPending: controller.isSkipTurnPending,
      placeCardActionStatus: controller.placeCardActionStatus,
      placeChallengeActionStatus: controller.placeChallengeActionStatus,
      skipTrackActionStatus: controller.skipTrackActionStatus,
      skipTurnActionStatus: controller.skipTurnActionStatus,
      roomState: controller.roomState,
      showHelperLabels: controller.showHelperLabels,
    },
    header: {
      closeRoomActionStatus: controller.closeRoomActionStatus,
      currentPlayerId: controller.currentPlayerId,
      handleCloseRoom: controller.handleCloseRoom,
      handleSkipTurn: controller.handleSkipTurn,
      isCloseRoomPending: controller.isCloseRoomPending,
      isSkipTurnPending: controller.isSkipTurnPending,
      leadingPlayers: controller.leadingPlayers,
      menuTabs: controller.menuTabs,
      roomState: controller.roomState,
      skipTurnActionStatus: controller.skipTurnActionStatus,
      showMiniStandings: controller.showMiniStandings,
      showPhaseChip: controller.showPhaseChip,
      showRoomCodeChip: controller.showRoomCodeChip,
      showTimelineHints: controller.showTimelineHints,
      showTurnNumberChip: controller.showTurnNumberChip,
      statusBadgeText: controller.statusBadgeText,
      statusDetailText: controller.statusDetailText,
      updateViewPreferences: controller.updateViewPreferences,
      visibleTimelineCardCount: controller.visibleTimelineCardCount,
      visibleTimelinePlayerId: controller.visibleTimelinePlayerId,
      visibleTimelineTtCount: controller.visibleTimelineTtCount,
      visibleTimelineTitle: controller.visibleTimelineTitle,
    },
    timeline: {
      header: {
        canChangeTimelineView: controller.canChangeTimelineView,
        canToggleView: controller.canToggleTimelineView,
        cardCount: controller.visibleTimelineCardCount,
        onToggleTimelineView: controller.setTimelineView,
        timelineView: controller.timelineView,
        title: controller.visibleTimelineTitle,
      },
      interaction: {
        challengeMarkerTone: controller.challengeMarkerTone,
        challengerChosenSlotIndex: controller.visibleChallengeChosenSlot,
        disabledSlotIndexes: controller.disabledTimelineSlots,
        onSelectSlot: controller.setSelectedSlotIndex,
        originalChosenSlotIndex: controller.visibleOriginalChosenSlot,
        previewCard: controller.visiblePreviewCard,
        previewSlotIndex: controller.visiblePreviewSlot,
        selectable: !controller.isViewingOwnTimeline && controller.canSelectSlot,
        selectedSlotIndex: controller.selectedSlotIndex,
      },
      render: {
        hiddenCardMode: controller.hiddenCardMode,
        revealedCardMode: controller.revealedCardMode,
        hint: controller.visibleTimelineHint,
        previewCardTransitionEvent: controller.previewCardTransitionEvent,
        timelinePreviewTransitionEvent: controller.timelinePreviewTransitionEvent,
        timelineCelebrationTransitionEvent:
          controller.timelineCelebrationTransitionEvent,
        showCorrectPlacementPreview: controller.showCorrectPlacementPreview,
        showCorrectionPreview: controller.showCorrectionPreview,
        showDevAlbumInfo: controller.isHost && controller.showDevAlbumInfo,
        showDevCardInfo: controller.isHost && controller.showDevCardInfo,
        showDevGenreInfo: controller.isHost && controller.showDevGenreInfo,
        showDevYearInfo: controller.isHost && controller.showDevYearInfo,
        showHint:
          controller.showTimelineHints && controller.visibleTimelineHint.length > 0,
        theme: controller.theme,
        timelineCards: controller.visibleTimelineCards,
        timelineView: controller.timelineView,
      },
    },
  };
}
