export const ClientToServerEvent = {
  AwardTt: "award_tt",
  BuyTimelineCardWithTt: "buy_timeline_card_with_tt",
  ClaimChallenge: "claim_challenge",
  CloseRoom: "close_room",
  ConfirmReveal: "confirm_reveal",
  CreateRoom: "create_room",
  GetRoomPreview: "get_room_preview",
  GetPlaylistTracks: "get_playlist_tracks",
  GenerateSpotifyCandidates: "generate_spotify_candidates",
  ImportPlaylist: "import_playlist",
  JoinRoom: "join_room",
  KickPlayer: "kick_player",
  ListRooms: "list_rooms",
  LoadCuratedPlaylist: "load_curated_playlist",
  OpenSpotifyPlaylist: "open_spotify_playlist",
  PlaceCard: "place_card",
  PlaceChallenge: "place_challenge",
  RefreshSpotifyToken: "refresh_spotify_token",
  PlaySpotifyTrack: "play_spotify_track",
  RegisterSpotifyPlaybackDevice: "register_spotify_playback_device",
  UnregisterSpotifyPlaybackDevice: "unregister_spotify_playback_device",
  RemovePlaylistTracks: "remove_playlist_tracks",
  RenameRoom: "rename_room",
  RequestSpotifyAuthUrl: "request_spotify_auth_url",
  ResolveChallengeWindow: "resolve_challenge_window",
  SearchSpotifyPlaylists: "search_spotify_playlists",
  SearchSpotifyMusic: "search_spotify_music",
  SkipTrackWithTt: "skip_track_with_tt",
  SkipTurn: "skip_turn",
  StartGame: "start_game",
  TransferHost: "transfer_host",
  UpdatePlayerProfile: "update_player_profile",
  UpdatePlayerSettings: "update_player_settings",
  UpdatePlaylistTrack: "update_playlist_track",
  UpdateRoomSettings: "update_room_settings",
  UseSpotifyCandidates: "use_spotify_candidates",
} as const;

export type ClientToServerEventName =
  (typeof ClientToServerEvent)[keyof typeof ClientToServerEvent];
